"""Type stubs for networkx - graph library."""

from collections.abc import Generator, Iterable, Iterator
from typing import Any, Literal

class NetworkXNoCycle(Exception): ...  # noqa: N818 - matches networkx API

class NodeDataView[Node]:
    def __iter__(self) -> Iterator[tuple[Node, dict[str, Any]]]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, node: Node) -> dict[str, Any]: ...

class NodeView[Node]:
    def __call__(self, data: bool = False) -> NodeView[Node]: ...
    def __iter__(self) -> Iterator[Node]: ...
    def __len__(self) -> int: ...
    def __contains__(self, node: Node) -> bool: ...
    def __getitem__(self, node: Node) -> dict[str, Any]: ...

class EdgeView[Node]:
    def __call__(self, data: bool = False) -> EdgeView[Node]: ...
    def __iter__(self) -> Iterator[tuple[Node, Node]]: ...
    def __len__(self) -> int: ...

class DiGraph[Node]:
    nodes: NodeView[Node]
    edges: EdgeView[Node]
    def __init__(self) -> None: ...
    def __contains__(self, node: Node) -> bool: ...
    def add_node(self, node_for_adding: Node, **attr: Any) -> None: ...
    def add_edge(self, u_of_edge: Node, v_of_edge: Node, **attr: Any) -> None: ...
    def remove_node(self, n: Node) -> None: ...
    def remove_edge(self, u: Node, v: Node) -> None: ...
    def has_edge(self, u: Node, v: Node) -> bool: ...
    def subgraph(self, nodes: Iterable[Node]) -> DiGraph[Node]: ...
    def reverse(self, copy: bool = True) -> DiGraph[Node]: ...
    def successors(self, n: Node) -> Iterator[Node]: ...
    def predecessors(self, n: Node) -> Iterator[Node]: ...
    def degree(self, nbunch: Node | None = None) -> int: ...

def dfs_postorder_nodes[Node](
    G: DiGraph[Node],  # noqa: N803 - matches networkx API
    source: Node | None = None,
    depth_limit: int | None = None,
) -> Generator[Node]: ...
def find_cycle[Node](
    G: DiGraph[Node],  # noqa: N803 - matches networkx API
    source: Node | None = None,
    orientation: Literal["original", "reverse", "ignore"] | None = None,
) -> list[tuple[Node, Node, Literal["forward", "reverse"]]]: ...
def descendants[Node](
    G: DiGraph[Node],  # noqa: N803 - matches networkx API
    source: Node,
) -> set[Node]: ...
